# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20171023_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepage',
            options={'verbose_name': 'Service page', 'verbose_name_plural': 'Services pages'},
        ),
    ]
