# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171013_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='main_image',
            new_name='header_image',
        ),
    ]
