# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blofpagegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blofpagegalleryimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
