# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 20:24
from __future__ import unicode_literals

import blog.models
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171013_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('h1', wagtail.wagtailcore.blocks.CharBlock(classanme='title', icon='title')), ('h2', wagtail.wagtailcore.blocks.CharBlock(classanme='title', icon='title')), ('h3', wagtail.wagtailcore.blocks.CharBlock(classanme='title', icon='title')), ('h4', wagtail.wagtailcore.blocks.CharBlock(classanme='title', icon='title')), ('h5', wagtail.wagtailcore.blocks.CharBlock(classanme='title', icon='title')), ('h6', wagtail.wagtailcore.blocks.CharBlock(classanme='title', icon='title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('aligned_image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock()), ('alignment', blog.models.ImageFormatChoiceBlock())), icon='image', label='Aligned image')), ('pullquote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.TextBlock('quote title')), ('attribution', wagtail.wagtailcore.blocks.CharBlock())))), ('raw_html', wagtail.wagtailcore.blocks.RawHTMLBlock(icon='code', label='Raw HTML')), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock(icon='code')))),
        ),
    ]
