# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpagerelatedlink',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
