# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20171012_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='formindexpage',
            name='index_subtitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
