# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepagemarketing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagemarketing',
            name='market_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
