# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20171011_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagemarketing',
            name='martket_button',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
