# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepagemarketing_martket_button'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagemarketing',
            old_name='martket_button',
            new_name='market_button',
        ),
    ]
