# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpage',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
